spring:
  application:
    name: create-address
  elasticsearch:
    rest:
      uris: localhost:9200
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
  cloud:
    gcp:
      project-id: YOUR_GCP_PROJECT_ID_HERE
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    root: INFO
    uk:
      gov:
        ons: INFO
    org:
      springframework:
        data:
          elasticsearch: INFO
aims:
  pubsub:
    subscription: new-address-subscription
  elasticsearch:
    index:
      name: new-addresses
  tokeniser:
    uri: http://localhost:8081
    path: /tokens?address={address}