spring:
  application:
    name: create-address
  elasticsearch:
    rest:
      uris: localhost:9200
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
  cloud:
    gcp:
      project-id:  census-ai-create-test-2
      
  servlet:
    multipart:
      max-file-size: 100MB
  thymeleaf:
    reactive:
      max-chunk-size: 8192
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    root: info
    uk:
      gov:
        ons: info
    org:
      springframework:
        data:
          elasticsearch: trace
aims:
  pubsub:
    subscription: new-address-subscription
  gcp:
    bucket: aims-create-test-2-bad-addresses
  elasticsearch:
    cluster:
      fat-enabled: true
    index:
      aux:
        name: new-addresses
      fat:
        name: hybrid_39_100316_1603452786355
      skinny:
        name: hybrid-skinny_39_100316_1607340534475
  tokeniser:
    uri: http://localhost:8081
    path: /tokens?address={address}